Repository pewpewnor/HyperSpace, pull requests merged in 2023-03, with the labels that each got.

#20 Fixing some components and added profile picture to Navbar
  src/components/navbar/AccountInformation.js
  src/components/navbar/AccountMore.js
  src/components/navbar/Navbar.js
  src/components/navbar/navbar.css
Labels: frontend

#28 Added CSS for Thread and Modify some logic for Navbar CSS
  src/App.js
  src/components/navbar/AccountInformation.js
  src/components/navbar/Navbar.js
  src/components/navbar/navbar.css
  src/components/thread/Thread.js
  src/components/thread/thread-style.css
  src/style.css
Labels: frontend

#36 Refactor user context value and format CSS file
  src/App.js
  src/components/navbar/AccountInformation.js
  src/components/thread/threadtext.css
  src/contexts/UserContext.js
Labels: high priority, frontend

#40 Refactor main page and myspace layout, display spaces according to data
  README.md
  src/components/channel/ChannelView.js
  src/components/channel/channelview.css
  src/components/navbar/AccountMore.js
  src/components/navbar/Navbar.js
  src/components/navbar/navbar.css
  src/components/space/MySpace.js
  src/components/space/Space.js
  src/components/space/SpaceView.js
  src/components/space/myspace.css
  src/components/space/space.css
  src/components/thread/Thread.js
  src/components/thread/thread.css
  src/components/ui/ChannelView-style.css
  src/components/ui/ChannelView.js
  src/components/ui/SpaceJoined-style.css
  src/components/ui/SpaceJoined.js
  src/components/ui/SpaceView-style.css
  src/components/ui/SpaceView.js
  src/data/userdata.js
  src/pages/home/Home.js
  src/pages/home/home.css
  src/style.css
Labels: high priority

#37 Sync branch main with branch dev
  .prettierignore
  .prettierrc
  README.md
  jsconfig.json
  package-lock.json
  package.json
  public/assets/hyperspace-logo.png
  public/assets/post-pic-1.png
  public/assets/profile-pic-1.jpg
  public/index.html
  public/manifest.json
  src/App.js
  src/App.test.js
  src/assets/placeholder.txt
  src/components/channel/ChannelView.js
  src/components/channel/channelview.css
  src/components/navbar/AccountInformation.js
  src/components/navbar/AccountMore.js
  src/components/navbar/Navbar.js
  src/components/navbar/navbar.css
  src/components/navbar/placeholder.txt
  src/components/placeholder.txt
  src/components/space/MySpace.js
  src/components/space/Space.js
  src/components/space/myspace.css
  src/components/space/space.css
  src/components/thread/Thread.js
  src/components/thread/ThreadText.js
  src/components/thread/thread.css
  src/components/thread/threadtext.css
  src/contexts/LocationContext.js
  src/contexts/UserContext.js
  src/data/channeldata.js
  src/data/placeholder.txt
  src/data/spacedata.js
  src/data/threaddata.js
  src/data/userdata.js
  src/index.js
  src/pages/home/Home.js
  src/pages/home/home.css
  src/pages/home/placeholder.txt
  src/pages/placeholder.txt
  src/pages/space/placeholder.txt
  src/pages/spacepage/SpacePage.js
  src/pages/spacepage/spacepage.css
  src/reportWebVitals.js
  src/setupTests.js
  src/style.css
  src/utils/date.js
  src/utils/find.js
  src/utils/number.js
  src/utils/placeholder.txt
Labels: low priority, frontend

#43 Added Space Banner, Fixing CSS for some components
  src/App.js
  src/components/space/Space.js
  src/components/space/spaceBanner.css
  src/components/space/spaceBanner.js
  src/components/thread/Thread.js
  src/components/thread/thread.css
  src/components/thread/threadtext.css
  src/pages/home/home.css
  src/pages/spacepage/SpacePage.js
  src/pages/spacepage/spacepage.css
Labels: frontend

#48 Fix thread in spacepace & mainpage, Fix navbar, Format
  src/App.js
  src/components/channel/ChannelView.js
  src/components/navbar/AccountInformation.js
  src/components/navbar/Navbar.js
  src/components/navbar/accountinformation.css
  src/components/navbar/navbar.css
  src/components/space/Space.js
  src/components/space/spaceBanner.css
  src/components/space/spaceBanner.js
  src/components/thread/Thread.js
  src/components/thread/thread.css
  src/components/thread/threadtext.css
  src/pages/home/Home.js
  src/pages/home/home.css
  src/pages/login/placeholder.txt
  src/pages/spacepage/SpacePage.js
  src/pages/spacepage/spacepage.css
Labels: frontend
